spring:
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
      exclude: static/**,public/**,templates/**
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
netty:
  port:11111
